/**
 * Deterministic large-estate generator (FR-51, NFR-22).
 *
 * FR-51 states the Cloud Connector hands back bodies up to 10 MB, and the
 * payload ceiling in `src/safety/truncate.ts` exists to survive exactly that.
 * A 10 MB JSON file is not something to commit — it is unreviewable and it
 * would dwarf every other file in the repository — so the estate is rebuilt in
 * memory from a fixed seed instead. NFR-22 requires the rebuild to be
 * byte-identical run to run, which rules out `Math.random`: the PRNG here is a
 * counter hashed with SHA-256, so element N is the same on every machine, every
 * platform and every process.
 *
 * The bulk fields matter as much as the item count. A downstream test proves
 * default field projection is load-bearing by asserting the *same* page is over
 * the ceiling unprojected and under it projected — which is only a real
 * assertion if the fields projection discards are what carry the weight. So the
 * fields named in `DEFAULT_PROJECTIONS` are deliberately small, and everything
 * else on each item is deliberately not.
 */
import { createHash } from 'node:crypto';

/** Fixed seed. Changing this changes every generated byte — don't, casually. */
export const LARGE_ESTATE_SEED = '5e6d0f1a2b3c4d5e6f708192a3b4c5d6';

/** Sized so `JSON.stringify` of the camera array clears 10 MB (FR-51). */
export const PROTECT_CAMERA_COUNT = 6000;

/** FR-51's stated shape for Network: comfortably more than 5 000 clients. */
export const NETWORK_CLIENT_COUNT = 6000;

const CAMERA_STATES = ['CONNECTED', 'CONNECTING', 'DISCONNECTED'];
const CAMERA_MODELS = ['UVC G4 Bullet', 'UVC G5 Dome', 'UVC AI Pro', 'UVC G4 Doorbell'];
const CLIENT_TYPES = ['WIRED', 'WIRELESS', 'VPN', 'TELEPORT'];
const VIDEO_MODES = ['default', 'highFps', 'sport'];
const SMART_DETECT_TYPES = ['person', 'vehicle', 'package', 'animal', 'licensePlate'];

/**
 * Counter-based PRNG. Deterministic by construction: the Nth value depends only
 * on the seed and N, never on wall clock, ordering or process state.
 *
 * @param {string} seedHex - Even-length hex string.
 * @returns {() => number} Successive floats in [0, 1).
 */
export function makeRng(seedHex) {
  let counter = 0;
  return () =>
    createHash('sha256')
      .update(seedHex, 'hex')
      .update(String(counter++))
      .digest()
      .readUInt32BE(0) / 0x1_0000_0000;
}

/**
 * @param {string} label
 * @returns {string} A seed derived from {@link LARGE_ESTATE_SEED}, so the two
 * generators never draw the same stream.
 */
function deriveSeed(label) {
  return createHash('sha256').update(LARGE_ESTATE_SEED, 'hex').update(label).digest('hex');
}

/**
 * @param {() => number} rng
 * @returns {string} A locally-administered MAC, colon-separated and uppercase.
 */
function macAddress(rng) {
  const octets = ['02'];
  for (let i = 0; i < 5; i += 1) {
    octets.push(Math.floor(rng() * 256).toString(16).padStart(2, '0').toUpperCase());
  }
  return octets.join(':');
}

/**
 * @param {() => number} rng
 * @param {number} index
 * @returns {string} A deterministic UUID-shaped identifier.
 */
function identifier(rng, index) {
  const hex = Math.floor(rng() * 0xffffffff).toString(16).padStart(8, '0');
  const tail = index.toString(16).padStart(12, '0');
  return `${hex}-4${hex.slice(0, 3)}-8${hex.slice(3, 6)}-${hex.slice(0, 4)}-${tail}`;
}

/**
 * @param {() => number} rng
 * @param {number} index
 * @returns {Record<string, unknown>} One Protect camera: the six
 * `DEFAULT_PROJECTIONS.camera` fields plus the nested settings tree a real
 * console returns, which is what pushes a page over the ceiling.
 */
function protectCamera(rng, index) {
  const state = CAMERA_STATES[index % CAMERA_STATES.length];
  return {
    id: identifier(rng, index),
    name: `Camera ${String(index).padStart(5, '0')}`,
    type: CAMERA_MODELS[index % CAMERA_MODELS.length],
    state,
    isConnected: state === 'CONNECTED',
    isRecording: state === 'CONNECTED' && index % 3 !== 0,
    modelKey: 'camera',
    mac: macAddress(rng),
    host: `10.${(index >> 16) & 0xff}.${(index >> 8) & 0xff}.${index & 0xff}`,
    isMicEnabled: index % 4 !== 0,
    micVolume: Math.floor(rng() * 100),
    videoMode: VIDEO_MODES[index % VIDEO_MODES.length],
    hdrType: index % 2 === 0 ? 'auto' : 'normal',
    hasPackageCamera: index % 5 === 0,
    firmwareVersion: `4.7${index % 10}.${index % 60}`,
    firmwareBuild: `${identifier(rng, index).slice(0, 8)}`,
    upSince: 1_700_000_000_000 + index * 1000,
    lastSeen: 1_760_000_000_000 + index * 1000,
    connectedSince: 1_759_000_000_000 + index * 1000,
    wiredConnectionState: { phyRate: 1000, phyRateMbps: 1000, isPoeEnabled: true, poeMode: 'auto' },
    featureFlags: {
      canAdjustIrLedLevel: true,
      canMagicZoom: index % 2 === 0,
      hasHdr: true,
      hasLedIr: true,
      hasLedStatus: true,
      hasLineCrossing: true,
      hasMic: true,
      hasMotionZones: true,
      hasPrivacyMask: true,
      hasSdCard: index % 3 === 0,
      hasSmartDetect: true,
      hasSpeaker: index % 2 === 1,
      smartDetectTypes: SMART_DETECT_TYPES,
      videoModes: VIDEO_MODES,
    },
    ispSettings: {
      aeMode: 'auto',
      brightness: 50,
      contrast: 50,
      denoise: 50,
      focusMode: 'ztrig',
      hue: 50,
      irLedLevel: 255,
      irLedMode: 'auto',
      saturation: 50,
      sharpness: 50,
      wdr: 1,
      zoomPosition: 0,
    },
    smartDetectSettings: { objectTypes: SMART_DETECT_TYPES, audioTypes: ['alrmSmoke', 'alrmCmonx'] },
    channels: [0, 1, 2].map((channelId) => ({
      id: channelId,
      name: ['High', 'Medium', 'Low'][channelId],
      enabled: true,
      isRtspEnabled: channelId === 0,
      width: [3840, 1920, 640][channelId],
      height: [2160, 1080, 360][channelId],
      fps: [30, 30, 15][channelId],
      bitrate: [6_000_000, 1_400_000, 300_000][channelId],
      minBitrate: 200_000,
      maxBitrate: 6_000_000,
      idrInterval: 4,
      videoId: ['video1', 'video2', 'video3'][channelId],
    })),
    stats: {
      rxBytes: Math.floor(rng() * 1e12),
      txBytes: Math.floor(rng() * 1e12),
      storage: { used: Math.floor(rng() * 1e11), rate: rng() * 100 },
      video: { recordingStart: 1_700_000_000_000, recordingEnd: 1_760_000_000_000 },
    },
  };
}

/**
 * @param {() => number} rng
 * @param {number} index
 * @returns {Record<string, unknown>} One Network client: the six
 * `DEFAULT_PROJECTIONS.client` fields plus the per-client telemetry a real
 * console attaches to every entry.
 */
function networkClient(rng, index) {
  const type = CLIENT_TYPES[index % CLIENT_TYPES.length];
  return {
    id: identifier(rng, index),
    name: `client-${String(index).padStart(5, '0')}`,
    type,
    macAddress: macAddress(rng),
    ipAddress: `10.${(index >> 16) & 0xff}.${(index >> 8) & 0xff}.${index & 0xff}`,
    connectedAt: new Date(1_760_000_000_000 + index * 1000).toISOString(),
    access: { type: index % 7 === 0 ? 'BLOCKED' : 'DEFAULT', policyApplied: 'ALLOW_ALL' },
    uplinkDeviceId: identifier(rng, index + PROTECT_CAMERA_COUNT),
    hostname: `client-${String(index).padStart(5, '0')}.lan.invalid`,
    oui: 'Ubiquiti Inc',
    network: { id: identifier(rng, index * 2), name: `VLAN ${index % 32}`, vlanId: index % 32 },
    uplink: {
      deviceName: `switch-${index % 64}`,
      port: index % 48,
      signalStrengthDbm: -30 - Math.floor(rng() * 60),
      noiseFloorDbm: -96,
      txRateMbps: Math.floor(rng() * 1200),
      rxRateMbps: Math.floor(rng() * 1200),
      channel: 36 + (index % 8) * 4,
      radio: type === 'WIRELESS' ? 'na' : null,
    },
    statistics: {
      rxBytes: Math.floor(rng() * 1e11),
      txBytes: Math.floor(rng() * 1e11),
      rxPackets: Math.floor(rng() * 1e8),
      txPackets: Math.floor(rng() * 1e8),
      rxRetries: Math.floor(rng() * 1e5),
      txRetries: Math.floor(rng() * 1e5),
      satisfactionPercent: Math.floor(rng() * 100),
      uptimeSeconds: Math.floor(rng() * 1e7),
    },
    fingerprint: {
      computedEngineId: index % 97,
      devIdOverride: null,
      familyName: 'Generic Device',
      osName: ['Linux', 'Windows', 'macOS', 'iOS', 'Android'][index % 5],
      vendorName: 'Ubiquiti Inc',
    },
  };
}

/**
 * @param {number} [count]
 * @returns {Array<Record<string, unknown>>} A bare top-level array, the exact
 * shape Protect's list endpoints return.
 */
export function generateProtectCameras(count = PROTECT_CAMERA_COUNT) {
  const rng = makeRng(deriveSeed('protect-cameras'));
  return Array.from({ length: count }, (_, index) => protectCamera(rng, index));
}

/**
 * @param {number} [count]
 * @returns {Array<Record<string, unknown>>} Client items, to be wrapped in
 * Network's `{count, data, limit, offset, totalCount}` envelope by the caller.
 */
export function generateNetworkClients(count = NETWORK_CLIENT_COUNT) {
  const rng = makeRng(deriveSeed('network-clients'));
  return Array.from({ length: count }, (_, index) => networkClient(rng, index));
}

/** @type {{ cameras: Array<Record<string, unknown>>, clients: Array<Record<string, unknown>> } | null} */
let memoized = null;

/**
 * Generate once per process and reuse. Regenerating per test would repeat the
 * multi-megabyte build for no benefit and risk the runner's 60 000 ms timeout.
 *
 * @returns {{ cameras: Array<Record<string, unknown>>, clients: Array<Record<string, unknown>> }}
 */
export function largeEstate() {
  if (memoized === null) {
    memoized = { cameras: generateProtectCameras(), clients: generateNetworkClients() };
  }
  return memoized;
}
